### ISSUE TITLE
UnsatisfiedLinkError by using SoftTone class

### ISSUE THREAD

**Issue by MaTr74** [Pi4J/pi4j-v1#110]
Hello,

Every time I'm using the SoftTone class I get a java.lang.UnsatisfiedLinkError. E. g. 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.SoftTone.softToneCreate(I)I
        at com.pi4j.wiringpi.SoftTone.softToneCreate(Native Method)
```

 or 

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.SoftTone.softToneWrite(II)V
        at com.pi4j.wiringpi.SoftTone.softToneWrite(Native Method)
```

The libpi4j.so seems to be loaded properly.

Thanks! Martin

**Comment by savageautomate** [comment]
verified defect

**Comment by savageautomate** [comment]
Fixed in https://github.com/Pi4J/pi4j/commit/4b18e8b6cf19642b6fb424cc0f17019e481436ee

Sample code:

```
    // first we must setup wiringPi
    com.pi4j.wiringpi.Gpio.wiringPiSetup();

    // next we can create a soft-tone pin and set a frequency
    com.pi4j.wiringpi.SoftTone.softToneCreate(1); 
    com.pi4j.wiringpi.SoftTone.softToneWrite(1,1000);
```

Oscilloscope capture of tone frequency:

![Image of WiringPi Software on oscilloscope](http://www.savagehomeautomation.com/storage/images/wiringpi-softtone.png)
