### ISSUE TITLE
RuntimeError - GpioFactory NotFoundException

### ISSUE THREAD

**Issue by SiAMSONG** [Pi4J/pi4j-v1#118]
hello
i need help..

i use JDK8,  pi4j version 0.0.5

I have to write a simple program, ( http://pi4j.com/example/listener.html )
A runtime error has occurred.
Do you not find com.pi4j.io.gpio.GpioFactory package.
Compiles fine.
Error message writing  >>

Exception in thread "main" java.lang.NoClassDefFoundError: com/pi4j/io/gpio.GpioFactory
               at expir.main(expir.java.14)
Caused by : java.ling.ClassNotFoundException : com.pi4j.io.gpio.GpioFactory
                  at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
                  at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
                 .....

10 minutes, did not compile because classpath, after deleting the package, and then reinstall it.

**Comment by savageautomate** [comment]
Please use the 1.0-SNAPSHOT version.  There are many fixes since 0.0.5.  This version will soon be released.
