### ISSUE TITLE
java.lang.ExceptionInitializerError

### ISSUE THREAD

**Issue by hbod8** [Pi4J/pi4j-v1#120]
I used the GPIO Event listen example right of your page and ran on it on my brand new raspberry pi B+ and this error occurred:

Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:47)
    at com.pi4j.io.gpio.GpioFactory.getDefaultProvider(GpioFactory.java:102)
    at com.pi4j.io.gpio.impl.GpioControllerImpl.<init>(GpioControllerImpl.java:67)
    at com.pi4j.io.gpio.GpioFactory.getInstance(GpioFactory.java:85)
    at security.Security(security.java:44)
    at security.main(security.java:154)
Caused by: java.lang.NullPointerException
    at com.pi4j.util.NativeLibraryLoader.load(NativeLibraryLoader.java:218)
    at com.pi4j.wiringpi.Gpio.<clinit>(Gpio.java:138)
    ... 6 more

after running:
javac -cp .:classes:/opt/pi4j/lib/'_' ... 
and then 
sudo java -cp .:classes:/opt/pi4j/lib/'_' ...

I first installed pi4j manually and the filesystem failed to setup, then I uninstalled it using the online version and re-installed it today and every thing seemed fine I ran:
cd /
then:
/opt/pi4j/lib/
and it returned it was a directory. And it contained JAR files.

I am running a recent (not newest) version of Raspbian. I downloaded it dec. 15 of this year.

**Comment by savageautomate** [comment]
I tested this today on my B+ and it seems to be working with the latest 1.0-SNAPSHOT build.

```
pi@rpi-b-plus /opt/pi4j/examples $ pi4j ListenGpioExample.java 
+ javac -classpath '.:classes:*:classes:/opt/pi4j/lib/*' -d . ListenGpioExample.java

pi@rpi-b-plus /opt/pi4j/examples $ pi4j ListenGpioExample
+ sudo java -classpath '.:classes:*:classes:/opt/pi4j/lib/*' ListenGpioExample

<--Pi4J--> GPIO Listen Example ... started.
 ... complete the GPIO #02 circuit and see the listener feedback here in the console.
```
