### ISSUE TITLE
Native library loader not working with JDK8 early release.

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#23]
Native library loader not working with JDK8 early release.
The following exception is thrown.

pi@raspberrypi /opt/pi4j/examples $ sudo java -classpath .:classes:/opt/pi4j/lib/'*' ControlGpioExample
<--Pi4J--> GPIO Control Example ... started.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libpi4j.so: /tmp/libpi4j.so: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1954)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1843)
        at java.lang.Runtime.load0(Runtime.java:792)
        at java.lang.System.load(System.java:1060)
        at com.pi4j.util.NativeLibraryLoader.loadLibraryFromResource(NativeLibraryLoader.java:289)
        at com.pi4j.util.NativeLibraryLoader.load(NativeLibraryLoader.java:148)
        at com.pi4j.wiringpi.Gpio.<clinit>(Gpio.java:138)
        at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:47)
        at com.pi4j.io.gpio.GpioFactory.getDefaultProvider(GpioFactory.java:97)
        at com.pi4j.io.gpio.impl.GpioControllerImpl.<init>(GpioControllerImpl.java:65)
        at com.pi4j.io.gpio.GpioFactory.getInstance(GpioFactory.java:80)
        at ControlGpioExample.main(ControlGpioExample.java:50)

**Comment by savageautomate** [comment]
Fixed in 0.0.5-SNAPSHOT
