### ISSUE TITLE
Testing PCA9685GpioServoExample on Raspberry PI 3 and Latest Jessie

### ISSUE THREAD

**Issue by MatsMRL** [Pi4J/pi4j-v1#231]
Hi
I'm using a Raspberry PI 3 on latest Raspbian Jessie.
I used the Easy/Preferred method install Pi4J (http://pi4j.com/install.html)
curl -s get.pi4j.com | sudo bash

I connected a Adafruit 16-Channel 12-bit PWM/Servo Driver to the GPIO pins of the PI. https://www.adafruit.com/products/815 
I first tested using it from the  Adafruit Python libraries and it works fine. I used some servos connceted to it and they work fine, so no software or hardware issues. 

Then I tried to execute this example using Pi4J
sudo java -classpath .:classes:/opt/pi4j/lib/'*' PCA9685GpioServoExample

but I get this error

pi@pi3:/opt/pi4j/examples $ sudo java -classpath .:classes:/opt/pi4j/lib/'*' PCA9685GpioServoExample
<--Pi4J--> PCA9685 Servo Tester Example ... started.
Exception in thread "main" java.lang.ArithmeticException: Non-terminating decimal expansion; no exact representable decimal result.
    at java.math.BigDecimal.divide(BigDecimal.java:1690)
    at com.pi4j.component.servo.impl.PCA9685GpioServoDriver.updateResolution(PCA9685GpioServoDriver.java:87)
    at com.pi4j.component.servo.impl.PCA9685GpioServoDriver.<init>(PCA9685GpioServoDriver.java:52)
    at com.pi4j.component.servo.impl.PCA9685GpioServoProvider.getServoDriver(PCA9685GpioServoProvider.java:69)
    at PCA9685GpioServoExample.<init>(PCA9685GpioServoExample.java:147)
    at PCA9685GpioServoExample.main(PCA9685GpioServoExample.java:59)

/Mats

**Comment by MatsMRL** [comment]
I installed the latest 1.1-SNAPSHOT and I got a different error. But then I used the i2c examples and got the PCA9685 to work.
