### ISSUE TITLE
GpioPinListenerDigital - Concurrent Rejected Execution Exception

### ISSUE THREAD

**Issue by mikebertiean** [Pi4J/pi4j-v1#251]
I set up a listener and the first time the method is run it works fine... however once the method finishes and gets called again at some future date I get an error:

```
Exception in thread "Thread-14" java.util.concurrent.RejectedExecutionException: Task com.pi4j.io.gpio.tasks.impl.GpioEventDispatchTaskImpl@11f409d rejected from java.util.concurrent.ThreadPoolExecutor@1d8bcce[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
at com.pi4j.concurrent.ShutdownDisabledExecutorWrapper.execute(ShutdownDisabledExecutorWrapper.java:113)
at com.pi4j.io.gpio.impl.GpioEventMonitorExecutorImpl.handlePinEvent(GpioEventMonitorExecutorImpl.java:91)
at com.pi4j.io.gpio.GpioProviderBase.dispatchPinDigitalStateChangeEvent(GpioProviderBase.java:332)
at com.pi4j.io.gpio.RaspiGpioProvider.pinStateChange(RaspiGpioProvider.java:206)
at com.pi4j.wiringpi.GpioInterrupt.pinStateChangeCallback(GpioInterrupt.java:126)
```

This is how the Listener is set up:

```
GpioPinListenerDigital listenerDigital = new GpioPinListenerDigital() {
            @Override
            public void handleGpioPinDigitalStateChangeEvent(GpioPinDigitalStateChangeEvent event) {
                // display pin state on console
                System.out.println(" --> GPIO PIN STATE CHANGE: " + event.getPin() + " = " + event.getState());
                if(event.getState().isHigh()) pulseCount++;
            }
        };
        gpio.addListener(listenerDigital, pin);
```

This is how the gpio is shut down:

```
gpio.removeListener(listenerDigital, pin);
gpio.unprovisionPin(pin);
gpio.shutdown();
```

On the first run it works fine. The second run, the gpio is initialized again and so is the pin however when the event is triggered I get the error shown above.

**Comment by mikebertiean** [comment]
Fixed by removing the gpio.shutdown() line.
