### ISSUE TITLE
Using Pi4j in a windows environment, getting the following error

### ISSUE THREAD

**Issue by Richard88christie** [Pi4J/pi4j-v1#292]
Hi Guys,

I am new to Raspberry Pi, I would like to learn how to get started in coding with java.
But as soon as I write the code and execute it I get the following error (The screen shot of the error is attached as well as at the bottom of the post ).
Can I use the Pi4j project in a windows environment to develop and then run it on the PI ?
Can some one please help me ?

![image](https://cloud.githubusercontent.com/assets/23167693/20568479/b4c7b86e-b1c2-11e6-941c-29f9a2c5d801.png)

Error-------------------------------------------------------
Nov 23, 2016 8:49:38 PM com.pi4j.util.NativeLibraryLoader load
SEVERE: Unable to load [libpi4j.so] using path: [/lib/raspberrypi/static/libpi4j.so]
java.lang.IllegalArgumentException: The path has to be absolute, but found: \lib\raspberrypi\static\libpi4j.so
	at com.pi4j.util.NativeLibraryLoader.loadLibraryFromClasspath(NativeLibraryLoader.java:125)
	at com.pi4j.util.NativeLibraryLoader.load(NativeLibraryLoader.java:97)
	at com.pi4j.wiringpi.Gpio.<clinit>(Gpio.java:189)
	at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:69)
	at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:51)
	at com.pi4j.platform.Platform.getGpioProvider(Platform.java:130)
	at com.pi4j.platform.Platform.getGpioProvider(Platform.java:123)
	at com.pi4j.io.gpio.GpioFactory.getDefaultProvider(GpioFactory.java:109)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.<init>(GpioControllerImpl.java:56)
	at com.pi4j.io.gpio.GpioFactory.getInstance(GpioFactory.java:91)
	at Blink.main(Blink.java:13)

Exception in thread "main" java.lang.UnsatisfiedLinkError: com.pi4j.wiringpi.Gpio.wiringPiSetup()I
	at com.pi4j.wiringpi.Gpio.wiringPiSetup(Native Method)
	at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:69)
	at com.pi4j.io.gpio.RaspiGpioProvider.<init>(RaspiGpioProvider.java:51)
	at com.pi4j.platform.Platform.getGpioProvider(Platform.java:130)
	at com.pi4j.platform.Platform.getGpioProvider(Platform.java:123)
	at com.pi4j.io.gpio.GpioFactory.getDefaultProvider(GpioFactory.java:109)
	at com.pi4j.io.gpio.impl.GpioControllerImpl.<init>(GpioControllerImpl.java:56)
	at com.pi4j.io.gpio.GpioFactory.getInstance(GpioFactory.java:91)
	at Blink.main(Blink.java:13)

**Comment by ghost** [comment]
This is not really a pi4j issue :

But Yes you can, first of all try catch your call on the pi4j in the catch output "unsuported platform."


 
        try {
           //your pi4j calls...
        } catch  (UnsatisfiedLinkError e){
            System.err.println("platform does not support this driver");      
        }
        catch (Exception e) {
            System.err.println("platform does not support this driver");
           
        }


After that create a bridge here some doc of what is a bridge http://www.oodesign.com/bridge-pattern.html 

concreteImplementator1 will be named in your case ForPi4j, and concreteImplementator2 wil be renamed ForUnsupportedPlatform. At startup of your program you will detect the system and choose what concrete implementation you will use. In the windows implementation you could just replace your call to pi4j by some trace, for example "gpio2 on".

To detect the system you are running in there is several possibility for example 

    getOsName().startsWith("Linux");

Or just make on simple test call to pi4j at the very begging of your program and if catched switch to the windows implementation.

But a better way could be to read the system properties or start your program with arguments, or env variable. you could use ant to build it for the raspberry. 


Because after testing it in eclipse you will need to execute it on the target raspberry where you do not have eclipse and ant or graddle or maven will helps you a lot, I recommand you to learn and use ant because it is lighter than maven.

I will release some example soon on my github just have a look on new incoming projects on it.

may @savageautomate could include an example of doing so in the example folder (or not since that isn't a real issue of the pi4j project.)

best regard

**Comment by Richard88christie** [comment]
Thanks very much for your response and recommendations Damien.

**Comment by savageautomate** [comment]
Yes, you can use Windows to write and compile your Java program using Pi4J and then run it on the Raspberry Pi.  You cannot (_at this time_) run it directly on a Windows/OSX platform since there are no Pi4J/WiringPi native libraries built for (_or compatible for_) those platforms.  That is unless you jump though extra hoops as @DamienMiras suggested.  

Here is an example of setting up a remote platform (the RPi) in NetBeans. 
https://netbeans.org/kb/docs/java/javase-embedded.html

Thanks, Robert
