### ISSUE TITLE
Odroid C1/C1+ GPIO Export Not Working

### ISSUE THREAD

**Issue by savageautomate** [Pi4J/pi4j-v1#298]
Original Issue Thread: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/pi4j/ZdHfxCDSJYQ

> Hi, I am having issues getting to run my application on an Odroid C1+ board running Ubuntu 14.04. The same error happens even when I run the GPIO input example provided.
> 
> Exception in thread "main" java.lang.RuntimeException: Unable to open GPIO export interface: No such file or directory
> 
>     at com.pi4j.wiringpi.GpioUtil.export(Native Method)
>     at com.pi4j.io.gpio.WiringPiGpioProviderBase.export(WiringPiGpioProviderBase.java:108)
>     at com.pi4j.io.gpio.OdroidGpioProvider.export(OdroidGpioProvider.java:157)
>     at com.pi4j.io.gpio.impl.GpioPinImpl.export(GpioPinImpl.java:158)
>     at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionPin(GpioControllerImpl.java:565)
>     at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionPin(GpioControllerImpl.java:538)
>     at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalInputPin(GpioControllerImpl.java:639)
>     at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalInputPin(GpioControllerImpl.java:667)
>     at com.pi4j.io.gpio.impl.GpioControllerImpl.provisionDigitalInputPin(GpioControllerImpl.java:679)
>     at odroid.c1.GpioInputExample.main(GpioInputExample.java:110)
> 

I looks like newer kernel builds have replaced the "aml_gpio" kernel module in favor of the standard GPIO file system interface.  (sometime after v3.10.96-143).  

Pi4J native sources need to be modified to use the standard `/sys/class/gpio` pseudo file system interfaces rather than `/sys/class/aml_gpio`

**Comment by savageautomate** [comment]
This fix is now available in the latest 1.2-SNAPSHOT build.
