### ISSUE TITLE
Exception on 2 pulses on 2 different ports  at same time (with possible correction)

### ISSUE THREAD

**Issue by wnojunior** [Pi4J/pi4j-v1#326]
This exception is raised only a few times.

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.add(ArrayList.java:441)
	at com.pi4j.io.gpio.impl.GpioScheduledExecutorImpl.pulse(GpioScheduledExecutorImpl.java:133)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:319)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:275)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:255)

My Suggestion:

Use of CopyOnWriteArrayList in com.pi4j.io.gpio.impl.GpioScheduledExecutorImpl.java line 50 and others points that uses this variable.
 
private static final ConcurrentHashMap<GpioPinDigitalOutput, CopyOnWriteArrayList<ScheduledFuture<?>>> pinTaskQueue = new ConcurrentHashMap<>();

**Comment by wnojunior** [comment]
The hash is thread safe, but the list no. Two threads can try delete items on same time.
