### ISSUE TITLE
I2CExample

### ISSUE THREAD

**Issue by hr3** [Pi4J/pi4j-v1#368]
Hi, I use
```
pi4j-1.2-SNAPSHOT.deb
Kernel = Linux 4.9.35-v7+
Platform = Raspberry Pi 3 Model B Rev 1.2

s$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (Zulu Embedded 8.20.0.42-linux-aarch32hf) (build 1.8.0_121-b42)
OpenJDK Client VM (Zulu Embedded 8.20.0.42-linux-aarch32hf) (build 25.121-b42, mixed mode, Evaluation)

$ lsmod
Module                  Size  Used by
i2c_bcm2708             5994  0
w1_therm                6401  0
bnep                   12051  2
hci_uart               20020  1
btbcm                   7916  1 hci_uart
bluetooth             365511  22 hci_uart,bnep,btbcm
brcmfmac              222874  0
brcmutil                9092  1 brcmfmac
cfg80211              543027  1 brcmfmac
rfkill                 20851  4 bluetooth,cfg80211
sg                     20825  0
snd_bcm2835            24427  0
snd_pcm                98501  1 snd_bcm2835
w1_gpio                 4818  0
snd_timer              23968  1 snd_pcm
snd                    70032  3 snd_timer,snd_bcm2835,snd_pcm
wire                   32619  2 w1_gpio,w1_therm
bcm2835_gpiomem         3940  0
cn                      5889  1 wire
i2c_bcm2835             7167  0
fixed                   3285  0
uio_pdrv_genirq         3923  0
uio                    10204  1 uio_pdrv_genirq
i2c_dev                 6913  0
ipv6                  408971  66

$ i2cdetect -V
i2cdetect version 3.1.1+SVN

$ i2cdetect -F 1
Functionalities implemented by /dev/i2c-1:
I2C                              yes
SMBus Quick Command              yes
SMBus Send Byte                  yes
SMBus Receive Byte               yes
SMBus Write Byte                 yes
SMBus Read Byte                  yes
SMBus Write Word                 yes
SMBus Read Word                  yes
SMBus Process Call               yes
SMBus Block Write                yes
SMBus Block Read                 no
SMBus Block Process Call         no
SMBus PEC                        yes
I2C Block Write                  yes
I2C Block Read                   yes

$ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: 40 -- -- -- -- -- -- -- 48 -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

$ i2cdetect -l
i2c-1   i2c             bcm2835 I2C adapter                     I2C adapter
```
have connected **GY-21** and **ADS1115** and get this error
```
************************************************************
************************************************************
                  <-- The Pi4J Project -->
                         I2C Example
************************************************************
************************************************************
------------------------------
|    PRESS CTRL-C TO EXIT    |
------------------------------
Found follow I2C busses: [1]
Unsupported I2C bus 0 required
Supported I2C bus 1 found
Unsupported I2C bus 2 required
Unsupported I2C bus 3 required
Unsupported I2C bus 4 required
Unsupported I2C bus 5 required
Unsupported I2C bus 6 required
Unsupported I2C bus 7 required
Unsupported I2C bus 8 required
Unsupported I2C bus 9 required
Unsupported I2C bus 10 required
Unsupported I2C bus 11 required
Unsupported I2C bus 12 required
Unsupported I2C bus 13 required
Unsupported I2C bus 14 required
Unsupported I2C bus 15 required
Unsupported I2C bus 16 required
Unsupported I2C bus 17 required
... reading ID register from TSL2561
Exception in thread "main" java.io.IOException: Remote I/O error
        at java.io.RandomAccessFile.write0(Native Method)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:489)
        at java.io.RandomAccessFile.writeByte(RandomAccessFile.java:991)
        at com.pi4j.io.i2c.impl.I2CBusImpl.lambda$readByte$2(I2CBusImpl.java:154)
        at com.pi4j.io.i2c.impl.I2CBusImpl.runBusLockedDeviceAction(I2CBusImpl.java:260)
        at com.pi4j.io.i2c.impl.I2CBusImpl.readByte(I2CBusImpl.java:153)
        at com.pi4j.io.i2c.impl.I2CDeviceImpl.read(I2CDeviceImpl.java:205)
        at I2CExample.main(I2CExample.java:133)
************************************************************
                           GOODBYE
************************************************************
```

**Comment by vimaleshbe** [comment]
I am also facing the same error 

`Exception in thread "main" java.io.IOException: Remote I/O error
        at java.io.RandomAccessFile.write0(Native Method)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:489)
        at java.io.RandomAccessFile.writeByte(RandomAccessFile.java:991)
        at com.pi4j.io.i2c.impl.I2CBusImpl.lambda$readByte$2(I2CBusImpl.java:154)
        at com.pi4j.io.i2c.impl.I2CBusImpl.runBusLockedDeviceAction(I2CBusImpl.java:260)
        at com.pi4j.io.i2c.impl.I2CBusImpl.readByte(I2CBusImpl.java:153)
        at com.pi4j.io.i2c.impl.I2CDeviceImpl.read(I2CDeviceImpl.java:205)
        at com.pi4j.gpio.extension.mcp.MCP23017GpioProvider.<init>(MCP23017GpioProvider.java:129)
        at com.pi4j.gpio.extension.mcp.MCP23017GpioProvider.<init>(MCP23017GpioProvider.java:113)
        at com.pi4j.gpio.extension.mcp.MCP23017GpioProvider.<init>(MCP23017GpioProvider.java:108)
        at relay.TestClass.main(TestClass.java:21)
`

**Comment by blazejkarwowski** [comment]
Same happening to me:
`
------------------------------
|    PRESS CTRL-C TO EXIT    |
------------------------------

Found follow I2C busses: [1]
Unsupported I2C bus 0 required
Supported I2C bus 1 found
Unsupported I2C bus 2 required
Unsupported I2C bus 3 required
Unsupported I2C bus 4 required
Unsupported I2C bus 5 required
Unsupported I2C bus 6 required
Unsupported I2C bus 7 required
Unsupported I2C bus 8 required
Unsupported I2C bus 9 required
Unsupported I2C bus 10 required
Unsupported I2C bus 11 required
Unsupported I2C bus 12 required
Unsupported I2C bus 13 required
Unsupported I2C bus 14 required
Unsupported I2C bus 15 required
Unsupported I2C bus 16 required
Unsupported I2C bus 17 required
... reading ID register from TSL2561
Exception in thread "main" java.io.IOException: Remote I/O error
        at java.io.RandomAccessFile.write0(Native Method)
        at java.io.RandomAccessFile.write(RandomAccessFile.java:489)
        at java.io.RandomAccessFile.writeByte(RandomAccessFile.java:991)
        at com.pi4j.io.i2c.impl.I2CBusImpl.lambda$readByte$2(I2CBusImpl.java:154)
        at com.pi4j.io.i2c.impl.I2CBusImpl.runBusLockedDeviceAction(I2CBusImpl.java:260)
        at com.pi4j.io.i2c.impl.I2CBusImpl.readByte(I2CBusImpl.java:153)
        at com.pi4j.io.i2c.impl.I2CDeviceImpl.read(I2CDeviceImpl.java:205)
        at I2CExample.main(I2CExample.java:133)
`

**Comment by cesarjhony** [comment]
Guys, this error is because the remote device does not respond.
Look at the address to see if is same of remote device.
In my case mcp23017 example has 0x21 instead of 0x20 in the MCP23017GpioProvider(I2CBus.BUS_1, 0x20);
I using raspberry pi zero w and MCP23017

**Comment by nanodeath** [comment]
Thanks for the pointer, @cesarjhony.

If you're extra special like me, you may need to *actually power the I2C device*. I thought because the power light was on, it was powered, but if you plug it in, the power light gets even brighter. Go figure.

**Comment by eitch** [comment]
I would also like to point out, that in some cases when you write something to an I2C device, the device might take longer to respond. This happens for instance when i write to an EEPROM. 

The solution is this little program here:

https://github.com/raspihats/raspihats/tree/master/clk_stretch

https://raspihats.com/i2c-hat/2016/02/16/raspberry-pi-i2c-clock-stretch-timeout.html

**Comment by savageautomate** [comment]
No further activity; closed.
