### ISSUE TITLE
Got an IndexOutOfBoundsException in GpioScheduledExecutorImpl

### ISSUE THREAD

**Issue by dapaulus** [Pi4J/pi4j-v1#389]
My application ran flawlessly for a while, but after a few hours I got the following:

Exception in thread "Thread-7" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.remove(ArrayList.java:492)
	at com.pi4j.io.gpio.impl.GpioScheduledExecutorImpl.init(GpioScheduledExecutorImpl.java:62)
	at com.pi4j.io.gpio.impl.GpioScheduledExecutorImpl.pulse(GpioScheduledExecutorImpl.java:114)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:319)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:275)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:265)
	at com.pi4j.io.gpio.impl.GpioPinImpl.pulse(GpioPinImpl.java:245)
	at nl.paulweb.ClockControllerImpl.shiftBit(ClockControllerImpl.java:87)
	at nl.paulweb.ClockControllerImpl.shiftToRegisters(ClockControllerImpl.java:67)
	at nl.paulweb.ClockControllerImpl.shifBCDToRegisters(ClockControllerImpl.java:36)
	at nl.paulweb.ClockThread.displayTime(ClockThread.java:50)
	at nl.paulweb.ClockThread.run(ClockThread.java:27)
	at java.lang.Thread.run(Thread.java:745)

and it stopped working. I re-implemented using somepin.high() and somepin.low() and it is now working properly for at least a day.

Given the random nature of this failure and after a quick look at the code, I guess it has something to do with thread safety. 

Version I am using:

        <dependency>
            <groupId>com.pi4j</groupId>
            <artifactId>pi4j-core</artifactId>
            <version>1.2-SNAPSHOT</version>
        </dependency>

from https://oss.sonatype.org/content/groups/public

**Comment by savageautomate** [comment]
Fixed in v1.3
