### ISSUE TITLE
NullPointerException at com.pi4j.io.gpio.GpioProviderBase.dispatchPinDigitalStateChangeEvent(GpioProviderBase.java:355)

### ISSUE THREAD

**Issue by wnojunior** [Pi4J/pi4j-v1#416]
- java.lang.NullPointerException
	at com.pi4j.io.gpio.GpioProviderBase.dispatchPinDigitalStateChangeEvent(GpioProviderBase.java:355)
	at com.pi4j.io.gpio.WiringPiGpioProviderBase.pinStateChange(WiringPiGpioProviderBase.java:290)
	at com.pi4j.wiringpi.GpioInterrupt.pinStateChangeCallback(GpioInterrupt.java:128)

In method removeAllListeners(), was implemented use of synchronized (listeners) and use a copy of listeners but dispatchPinDigitalStateChangeEvent() and dispatchPinAnalogValueChangeEvent() not.

**Comment by savageautomate** [comment]
Fixed in commit https://github.com/Pi4J/pi4j/commit/2fe563bc2021ba9e4a588d07c2583775c1fc3a21
for upcoming Pi4J v1.3 release.

See also: https://github.com/Pi4J/pi4j/issues/457
