### ISSUE TITLE
PCA9685GpioProvider java.lang.NullPointerException

### ISSUE THREAD

**Issue by tursom** [Pi4J/pi4j-v1#430]
Exception in thread "main" java.lang.NullPointerException
	at com.pi4j.gpio.extension.pca.PCA9685GpioProvider.validatePin(PCA9685GpioProvider.java:314)
	at com.pi4j.gpio.extension.pca.PCA9685GpioProvider.setPwm(PCA9685GpioProvider.java:187)
	at cn.tursom.cardrive.control.MainKt.main(main.kt:24)

**Comment by pg-adm1n** [comment]
Hi, please refer [https://github.com/Pi4J/pi4j/issues/422](https://github.com/Pi4J/pi4j/issues/422) to use setMode first.
I will push a pr for this issue.
And I think you can close this ticket.
Thanks.

**Comment by TangPere** [comment]
Hi, please refer [https://github.com/Pi4J/pi4j/issues/422](url) to use setMode first.
I will push a pr for this issue.
And I think you can close this ticket.
Thanks.

**Comment by savageautomate** [comment]
Adding missing `export` overloaded method to set pin mode by default at time of pin provisioning.
