### ISSUE TITLE
SystemInfoExample errors because SystemInfo.getCpuInfo() is case-sensitive

### ISSUE THREAD

**Issue by gitgrimbo** [Pi4J/pi4j-v1#63]
The error when running `SystemInfoExample`:

```
----------------------------------------------------
HARDWARE INFO
----------------------------------------------------
Serial Number     :  000000003e433a87
CPU Revision      :  7
CPU Architecture  :  7
CPU Part          :  0xb76
CPU Temperature   :  51.4
CPU Core Voltage  :  1.2
MIPS              :  2.00
[WARNING]
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.RuntimeException: Invalid target: Processor
        at com.pi4j.system.SystemInfo.getCpuInfo(SystemInfo.java:78)
        at com.pi4j.system.SystemInfo.getProcessor(SystemInfo.java:82)
        at SystemInfoExample.main(SystemInfoExample.java:58)
        ... 6 more
```

Why does this happen? Because `SystemInfo.getCpuInfo()` uses a `Map<String, String>`, for which the `containsKey()` method is case-sensitive, and `/proc/cpuinfo` returns lowercase `processor` (in my case):
(https://github.com/Pi4J/pi4j/blob/release/0.0.5/pi4j-core/src/main/java/com/pi4j/system/SystemInfo.java#L74)

```
pi@raspberrypi ~/java/pi4j/pi4j-example $ cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 2.00
Features        : swp half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7

Hardware        : BCM2708
Revision        : 0002
Serial          : 000000003e433a87
```

A simple fix would be to make the keys all lower case (assuming you are not relying on case sensitivity for something):

```
    private static String getCpuInfo(String target) throws IOException, InterruptedException {
        target = target.toLowerCase();
    ...
                        cpuInfo.put(parts[0].trim().toLowerCase(), parts[1].trim());
    ...

        if (cpuInfo.containsKey(target)) {
```

**Comment by andypiper** [comment]
Just hit the same issue here, thanks for the debugging work. Not sure whether these issues are being looked at though :-/

**Comment by dulichan** [comment]
I also encountered the issue. Seems like the fix by @gitgrimbo will fix the problem. Why don't we merge it to pi4j and release it to nexus.

Cheers~
