### ISSUE TITLE
SystemInfo reports an error in getProcessor() on Raspi Rev.B

### ISSUE THREAD

**Issue by fpapleux** [Pi4J/pi4j-v1#74]
Probably trivial to fix.  Code is looking for "Processor" but the system holds "processor" in cpuinfo, without the capital P.

Error message below:
Exception in thread "main" java.lang.RuntimeException: Invalid target: Processor
    at com.pi4j.system.SystemInfo.getCpuInfo(SystemInfo.java:78)
    at com.pi4j.system.SystemInfo.getProcessor(SystemInfo.java:82)
    at open.I2C.systemInfo(Unknown Source)
    at open.App.main(Unknown Source)

a cat of my /proc/cpuinfo reports:
processor   : 0
model name  : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS    : 2.00
Features    : swp half thumb fastmult vfp edsp java tls 
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part    : 0xb76
CPU revision    : 7

Hardware    : BCM2708
Revision    : 000d
Serial      : 00000000f25b09b7

**Comment by aviadlich** [comment]
The fix should be to ask for "model name"
The processor indicates something else

**Comment by savageautomate** [comment]
Fixed in 39d6ba1
